Update tsv exporter to filter other nodes based on given filter
CBIIT/ctos-dataops-pipelines pull request #7
Opened 2024-11-05 14:44 UTC by wfy1997

2024-11-19 15:13 UTC, n2iw commented on config/neo4j_data_tsv_exporter_config_example.yaml
> +    filter_related_nodes: FALSE #do not need this section if the user want the where query filter the related nodes
May I suggest we use lower case "false"? I know YAML support a lot of formats for boolean, but I personally think lower case "false" is a little cleaner indication that is a boolean.

2024-11-19 15:13 UTC, n2iw commented on neo4j_data_tsv_exporter.py
> +    def dfs(current, path, visited):
Is this intended to be defined inside "find_all_paths" function?

2024-11-19 15:20 UTC, wfy1997 commented on config/neo4j_data_tsv_exporter_config_example.yaml
> +    filter_related_nodes: FALSE #do not need this section if the user want the where query filter the related nodes
This is changed

2024-11-19 15:22 UTC, wfy1997 commented on neo4j_data_tsv_exporter.py
> +    def dfs(current, path, visited):
Yes it is

2024-12-16 23:06 UTC, n2iw requested changes
1. Please rename the script to tsv_exporter.py, as we'll need to support both Neo4j and Memgraph
2. Please make configuration file path/name a command line argument instead of hard coded.
3. Please allow using environment variable for username and password
4. Please order the columns, here is my suggested order: 
    - type
    - relationship columns
    - id field
    - other properties

2025-02-04 17:59 UTC, n2iw requested changes

2025-02-04 17:59 UTC, n2iw commented on config/neo4j_data_tsv_exporter_config_example.yaml
> +  bolt_port: "bolt://localhost:7687"
I suggest renaming this to bolt_url or similar, bolt_port will confuse user what value is needed.

2025-02-04 19:38 UTC, wfy1997 commented on config/neo4j_data_tsv_exporter_config_example.yaml
> +  bolt_port: "bolt://localhost:7687"
Renaming "bolt_port" to "bolt_url" was in the latest commit.

2025-02-04 19:43 UTC, n2iw approved these changes
LGTM

2025-02-04 19:43 UTC, merged